### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by IvLaptev** [TNT-Group/InLife-Back#1]
**Цель:** реализовать авторизацию с использованием JWT токена.

**Задачи:**
- [x] обработка пути для авторизации;

- [x] создание, хранение и отправка пользователю JWT токена;

- [x] хранение в БД хэша пароля;

- [x] защита публичных путей.

**Comment by IvLaptev** [comment]
Материалы:
27 апр. 2020 - [https://medium.com/zero-equals-false/protect-rest-apis-with-spring-security-and-jwt-5fbc90305cc5](https://medium.com/zero-equals-false/protect-rest-apis-with-spring-security-and-jwt-5fbc90305cc5)
5 мар. 2016 - [https://habr.com/ru/post/278411/](https://habr.com/ru/post/278411/)

**Comment by red-bird** [comment]
Лежит на ветке develop
